{
 "title": "Skyblock Bazaar",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "item_id",
    "query": {
     "query": "label_values(skyblock_item{job=\"skyblockexporter\"},item_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sell/Buy orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{item_id=\"$item_id\",job=\"skyblockexporter\", type=\"buyOrders\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{item_id=\"$item_id\",job=\"skyblockexporter\", type=\"sellOrders\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sell/Buy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Coins" } },
   "targets": [
    {
     "expr": "{item_id=\"$item_id\",job=\"skyblockexporter\", type=\"sellPrice\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{item_id=\"$item_id\",job=\"skyblockexporter\", type=\"buyPrice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sell/Buy Amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Items" } },
   "targets": [
    {
     "expr": "{item_id=\"$item_id\",job=\"skyblockexporter\", type=\"sellVolume\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{item_id=\"$item_id\",job=\"skyblockexporter\", type=\"buyVolume\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}